Flash_loader: increase wait rounds for slow boards
stlink-org/stlink pull request #1085
Opened 2021-01-14 10:55 UTC by seeseemelk

Certain systems can take a while to boot and flash (because of a slow power supply or because the core is running at a lower clock speed).
Commit b8813fab9734521a1857189aab5dbf2a30d37ea4 broke st-link for several of our boards. Increasing the `WAIT_ROUNDS` define by a little fixes the issues.

This was tested on a custom board with an STM32L471 and a custom board with an STM32L496.

2021-01-17 18:21 UTC, Nightwalker-87 commented
I'll probably not change this unless there has been widespread testing with various other board types and / or programmers.
This parameter has been changed several times which not only lead to improvements but also introduced side effects.
I'll leave this open for others in the community to have their say. Should there be a common sense on this, we may change it.

2021-01-18 13:44 UTC, chenguokai commented
> Commit b8813fa broke st-link for several of our boards. Increasing the WAIT_ROUNDS define by a little fixes the issues.

I am a bit confused. It seems that this particular commit does not change the wait time ideally, without considering the operating system scheduler and the function call cost which may cause the sleep time to be longer than expected. 

Anyway, since there are some boards that may be affected by this timing issue, I think increasing this period is fine.

2021-01-18 16:00 UTC, Ant-ON reviewed
@seeseemelk I think it's better to rewrite this part to use time_ms(). This will make possible to set the timeout in ms.
https://github.com/stlink-org/stlink/blob/4bfaab0ea993fe86da9f2aef612036adcf8ef58d/src/stlink-lib/helper.h#L4

2021-01-18 20:02 UTC, Nightwalker-87 commented
@Ant-ON Sounds like a good idea to me. :+1:

2021-02-18 22:52 UTC, Nightwalker-87 requested changes
I agree on the idea to rewrite this part in order to have to have a flexible solution.

2021-02-18 22:53 UTC, Nightwalker-87 commented
@slyshykO: What's your opinion on this?

2021-02-20 07:19 UTC, slyshykO approved these changes

2021-02-20 08:07 UTC, slyshykO commented
> @slyshykO: What's your opinion on this?

I am Ok with increasing wait time.

2021-02-21 20:39 UTC, Nightwalker-87 commented
@seeseemelk: Are you going to address the proposal from @Ant-ON ?

2021-03-04 16:09 UTC, seeseemelk commented
I'm afraid I don't really have the time to focus on this at the moment, especially given that we are switching from ST-Links to J-Links.

2021-03-06 15:07 UTC, Nightwalker-87 approved these changes
I'm going to let this pass, but shall there be any regression bug reports, that point back to this, we should not continue to tune this setting frequently.

2021-03-06 15:07 UTC, merged