CMake: Avoid hard-wired /usr/local/share
stlink-org/stlink pull request #1325
Opened 2023-08-15 08:46 UTC by gollux

Instead of defining own CMAKE_INSTALL_SHAREDIR, use existing CMAKE_INSTALL_FULL_DATADIR.

This way, CMAKE_INSTALL_PREFIX is respected.

2023-08-15 09:57 UTC, gszy requested changes
Looks OK except an indentation issue.

2023-08-15 09:57 UTC, gszy commented on src/stlink-gui/CMakeLists.txt
Please restore spaces-based indentation.

2023-08-15 10:46 UTC, gollux commented on src/stlink-gui/CMakeLists.txt
Sorry. Fixed.

2023-08-15 10:53 UTC, gszy approved these changes

2023-08-18 17:40 UTC, Nightwalker-87 commented
@gollux: Thanks for your contribution. The change looks fine to me.
However we should add a note in our tutorial on how to select a custom install path (e.g. link to https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) to point users to it, in case they are not familiar with CMake.

2023-08-18 17:40 UTC, Nightwalker-87 approved these changes

2023-09-01 20:41 UTC, Nightwalker-87 commented
I'll update the documentation afterwards.

2023-09-01 20:41 UTC, merged