add a graceful way to terminate st-util
stlink-org/stlink pull request #1395
Opened 2024-05-11 17:47 UTC by AJ528

if `st-util` is requested to close using SIGTERM, do so and exit with status code 0.

2024-05-12 15:40 UTC, Nightwalker-87 approved these changes

2024-05-13 03:46 UTC, Ant-ON requested changes
With such changes, `(void)signum;` is not required

2024-05-13 16:08 UTC, AJ528 commented
> With such changes, `(void)signum;` is not required

I'll be honest, I don't really know what that line is doing. It comes after `exit()` so I'm assuming it never gets run. In the spirit of "change as few things as possible" I didn't modify it, but if it serves no purpose I'm happy to remove the line.

2024-05-13 16:16 UTC, Ant-ON commented
@AJ528 this line suppress the warning about `signum` argument not used.

2024-05-13 19:24 UTC, AJ528 commented
alright, I removed `(void) signum;`

2024-05-13 21:00 UTC, Nightwalker-87 approved these changes

2024-05-14 02:42 UTC, Ant-ON approved these changes

2024-05-14 02:42 UTC, Ant-ON approved these changes

2024-05-29 19:29 UTC, merged