Re-add support for STM32F411xC/xE option bytes read/write
stlink-org/stlink pull request #1422
Opened 2024-08-27 11:54 UTC by AkshayPatwardhan

Fix STM32F411xC/xE chip file.

For some reason, support for STM32F411 was removed along the way? As far as I can tell - this was supported via #1141  but looks like it got removed along the way.

2024-08-27 11:55 UTC, AkshayPatwardhan commented
Sorry, just noticed i commited .DS_Store too. Please remove it when you review this PR.

2024-08-27 11:55 UTC, AkshayPatwardhan commented
Sorry.... My first PR...

2024-10-03 19:20 UTC, Nightwalker-87 requested changes
Please delete the .DS_Store files on your current branch and subsequently push it to update this PR.

2024-10-03 19:20 UTC, Nightwalker-87 commented on config/.DS_Store
Please delete this file on your current branch and subsequently push it to update this PR.

2024-10-03 19:20 UTC, Nightwalker-87 commented on .DS_Store
Please delete this file on your current branch and subsequently push it to update this PR.

2024-10-04 04:43 UTC, AkshayPatwardhan commented
Removed .DS_Store files

2024-10-11 20:23 UTC, Nightwalker-87 approved these changes

2024-10-11 20:35 UTC, merged